### ISSUE TITLE
Unhandled exception while quitting Vocaluxe

### ISSUE THREAD

**Issue by Stefan1200-de** [Vocaluxe/Vocaluxe#320]
Now I got time to post this error here:
![image](https://user-images.githubusercontent.com/15168351/30880119-d72db67a-a301-11e7-8207-18f54b5a1ed6.png)

I had this error already with the Vocaluxe July 2017 nightly on quitting Vocaluxe. But not everytime, just maybe every third time I exit Vocaluxe. This time I had it with the beta 2 of Vocaluxe from early September 2017. Using Vocaluxe x64 on Windows 10 1703.

Error.log:
```
Error-Log Vocaluxe 'Blue Sunrise' 0.4.0.beta2 (x64) (0.4.0.beta2-0-g01fa98a) 26.09.2017 21:20:31
63) Unhandled exception: Es wurde versucht, im geschützten Speicher zu lesen oder zu schreiben. Dies ist häufig ein Hinweis darauf, dass anderer Speicher beschädigt ist.   bei PortAudioSharp.PortAudio.Pa_CloseStream(IntPtr stream)
   bei Vocaluxe.Lib.Sound.CPortAudioHandle.CloseStream(IntPtr stream)
   bei Vocaluxe.Lib.Sound.Record.PortAudio.CPortAudioRecord.Close()
   bei Vocaluxe.Base.CRecord.Close()
   bei Vocaluxe.CMainProgram._CloseProgram()
   bei Vocaluxe.CMainProgram.Main(String[] args)
64) Error during shutdown!: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei Vocaluxe.Base.CBvideo.Pause(CVideoStream stream)
   bei VocaluxeLib.Menu.CMenu._PauseBG()
   bei VocaluxeLib.Menu.CMenu.OnClose()
   bei Vocaluxe.Base.CGraphics.Close()
   bei Vocaluxe.CMainProgram._CloseProgram()
```

System information:
[DxDiag.txt](https://github.com/Vocaluxe/Vocaluxe/files/1334718/DxDiag.txt)

**Comment by Stefan1200-de** [comment]
Still occur with:
Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-0-g41cf7a5)

**Comment by Stefan1200-de** [comment]
I guess this is the crashdump about this issue. It is a 7zip file, but renamed to .zip, because I was unable to upload .7z files.

[Vocaluxe.exe.4880.dmp.zip](https://github.com/Vocaluxe/Vocaluxe/files/1352529/Vocaluxe.exe.4880.dmp.zip)

**Comment by lukeIam** [comment]
@Stefan1200-de 

Thanks for providing the dump - I try to distillate the crash circumstances out of it.

**Comment by lukeIam** [comment]
@Stefan1200-de 

Until the fix is merged you can test with this build:
https://ci.appveyor.com/project/VocaluxeBuildBot/vocaluxe/build/176-fpumidfi

**Comment by lukeIam** [comment]
Looks like it still crashes sometimes if:
1. Mic is unplugged while singing
2. Mic is re-plugged
3. Start a new song
4. Back to 1. and loop a few times
5. Vocaluxe is closed normally
6. Crash (in the unmanged part - read protected memory)

We should wait with #325 until I fix this.

**Comment by lukeIam** [comment]
> We should wait with #325 until I fix this.

Should be fixed (at least we should not longer crash)

**Comment by Stefan1200-de** [comment]
That build is compatible with the 0.4.0 release?

**Comment by lukeIam** [comment]
> That build is compatible with the 0.4.0 release?

Yes...
https://ci.appveyor.com/project/VocaluxeBuildBot/vocaluxe/build/176-flceldfd

**Comment by Stefan1200-de** [comment]
@lukeIam Still happens with your version from 4. October 2017.

> 185) Unhandled exception: Es wurde versucht, im geschützten Speicher zu lesen oder zu schreiben. Dies ist häufig ein Hinweis darauf, dass anderer Speicher beschädigt ist.   bei PortAudioSharp.PortAudio.Pa_CloseStream(IntPtr stream)
>    bei Vocaluxe.Lib.Sound.CPortAudioHandle.CloseStream(IntPtr stream)
>    bei Vocaluxe.Lib.Sound.Record.PortAudio.CPortAudioRecord.Close()
>    bei Vocaluxe.Base.CRecord.Close()
>    bei Vocaluxe.CMainProgram._CloseProgram()
>    bei Vocaluxe.CMainProgram.Main(String[] args)
> 186) Error during shutdown!: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>    bei Vocaluxe.Base.CBvideo.Pause(CVideoStream stream)
>    bei VocaluxeLib.Menu.CMenu._PauseBG()
>    bei VocaluxeLib.Menu.CMenu.OnClose()
>    bei Vocaluxe.Base.CGraphics.Close()
>    bei Vocaluxe.CMainProgram._CloseProgram()

**Comment by flokuep** [comment]
After your latest commit Vocaluxe throws an exception (stream is null) and doesn't start anymore if there are some missing videos files (like intro...)

**Comment by lukeIam** [comment]
> After your latest commit Vocaluxe throws an exception (stream is null) and doesn't start anymore if there are some missing videos files (like intro...)

Thanks - I haven't tested this case.

**Comment by lukeIam** [comment]
> After your latest commit Vocaluxe throws an exception (stream is null) and doesn't start anymore if there are some missing videos files (like intro...)
> Thanks - I haven't tested this case.

Should be fixed now:
https://github.com/Vocaluxe/Vocaluxe/commit/ce4529325bc1e8eec642a2c0ebbf1f40770c105e

**Comment by flokuep** [comment]
Thanks.
